[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_message_hub = "2SgSRG9x8R76BFwgFogkWVqxAkg2mZXQayjGHpMp7BUM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
